### ISSUE TITLE
failure using  for (auto _ : state)

### ISSUE THREAD

**Issue by tamarlev** [google/benchmark#506] opened 2017-12-26 23:16 UTC
Hello,

I downloaded the example of benchmark in the README file:
#include <benchmark/benchmark.h>

static void BM_StringCreation(benchmark::State& state) {
  for (auto _ : state)
    std::string empty_string;
}
// Register the function as a benchmark
BENCHMARK(BM_StringCreation);

// Define another benchmark
static void BM_StringCopy(benchmark::State& state) {
  std::string x = "hello";
  for (auto _ : state)
    std::string copy(x);
}
BENCHMARK(BM_StringCopy);

BENCHMARK_MAIN();

and I get an error using 'for (auto _ : state)' 
error C3312: no callable 'begin' function found for type 'benchmark::State'
error C3312: no callable 'end' function found for type 'benchmark::State'

do you have any idea how to solve this?
also using that 'for (auto _ : state)'  is better then using 'while(state.KeepRunning())
what is the benefit of using 'while(state.KeepRunning())?when will you use it?

Thanks

**Comment by lijinpei** [comment] 2017-12-27 05:47
I can't reproduce the compiler error on my local machines, that's the command line you use to compile the code ?

**Comment by EricWF** [comment] 2017-12-27 05:49
You likely don't have a new enough version of the library. I've seen that exact error when mistakenly using old versions.

**Comment by EricWF** [comment] 2018-01-04 22:23
Closing as FIXED, since I'm assuming my comment is correct.

Please re-open if I was mistaken.

**Closed by EricWF** 2018-01-04 22:23 UTC
