### ISSUE TITLE
Multiple re-running of benchmarks is unexpected and slow

### ISSUE THREAD

**Issue by sztomi** [google/benchmark#330] opened 2016-12-29 19:28 UTC
I have a benchmark that I want to run on exactly one thread. I can't run it on many threads because the benchmark uses a unique system resource (a TCP port) that it would wait for. I tried the following:

```cpp
static void rpclib_get_answer(benchmark::State& state) {
  printf("start\n");
  rpclib_bench fixture;
  while (state.KeepRunning())
      fixture.get_answer();
}
BENCHMARK(rpclib_get_answer)->Threads(1);
```

also `ThreadRange(1,1)`, and also using a real fixture with BENCHMARK_F. The output is always the same:

```
Run on (4 X 2700 MHz CPU s)
2016-12-29 20:29:44
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
Benchmark                            Time           CPU Iterations
------------------------------------------------------------------
start
start
start
start
start
```

And the benchmark gets stuck.
Is this a bug or am I misunderstanding something?

**Comment by EricWF** [comment] 2016-12-29 19:33
I think you're misunderstanding. The library runs each benchmark multiple times with increasing number of iterations in order to determine how many repetitions are needed to get a large enough sample. What you're observing is those runs. One thread is still being used (Add a `printf("finished\n);` to observe this).

**Comment by sztomi** [comment] 2016-12-29 19:39
I see. It seems though that it is running the benchmark for a rather long time (I've been running it for around 5 minutes now, which takes a lot longer than the 100 repetitions times 5000 iterations that I used with another benchmarking framework). Is there a way to specify a maximum time for a benchmark?

**Comment by EricWF** [comment] 2016-12-29 19:47
Right, so the library is going to attempt to run each benchmark for `0.5` seconds by default. Repeating until it gets above that, which is probably requires a lot more than `5000` iterations.

The minimum time can be changed using `--benchmark_min_time=0.1` (or w/e value you wish).

Also see:
 * https://github.com/google/benchmark#controlling-number-of-iterations
 * [`--benchmark_min_time=N.N`](https://github.com/google/benchmark/blob/master/src/benchmark.cc#L58)
* [`Benchmark::MinTime(N.N)`](https://github.com/google/benchmark/blob/master/include/benchmark/benchmark_api.h#L537)

**Comment by sztomi** [comment] 2016-12-29 20:04
Thanks, I was a bit confused by what "minimum time" meant. However, I'm observing some weird behavior (to me at least): While trying to find a reasonable MinTime value, I found that 0.025 runs in an instance (producing around 5800 iterations), but 0.03 never seems to stop. Shouldn't increasing the mintime increase the run time roughly linearly?

**Comment by EricWF** [comment] 2016-12-29 20:17
>  Shouldn't increasing the mintime increase the run time roughly linearly?

They should roughly increase together but the actual relationship may not be linear.

> , I found that 0.025 runs in an instance (producing around 5800 iterations), but 0.03 never seems to stop.

That sounds like a bug. Could you provide a full reproducer?

**Comment by sztomi** [comment] 2016-12-29 20:22
It's very much work in progress, but hopefully it can be built on other systems: https://github.com/rpclib/benchmarks/tree/gbenchmark

```
mkdir build && cd build
conan install .. --build missing
cmake ..
make
```

Most conan packages were only tested on Linux, so I suggest sticking to that.

**Comment by EricWF** [comment] 2016-12-29 20:40
A minimal reproducer would be greatly preferred and appreciated.

**Comment by sztomi** [comment] 2016-12-29 20:56
I can't produce a smaller repro right now, unfortunately, but it's not a very complicated code. 

Furthermore, it seems that adding a sleep (to get_answer in target_code.cc) will make the problem disappear. That's a good enough workaround for me. Since I'll likely commit more on this branch, here is the commit that exhibits the behavior:  https://github.com/rpclib/benchmarks/tree/c6a29189fa7290d3d288eba3150176ed01a0cb3a

**Comment by EricWF** [comment] 2016-12-29 21:02
I can't build your project on Linux due to this error:

> /home/eric/other-workspace/rpc-bench/include/thrift/ThriftServiceBenchmark.h:10:39: fatal error: thrift/TDispatchProcessor.h: No such file or directory

I'm on the `gbenchmark` branch and have installed all the requested projects using conan.

**Comment by EricWF** [comment] 2016-12-29 21:09
Looks like conan isn't adding the proper include path for `thrift`.

I see `-I/home/eric/.conan/data/thrift/0.9.3/sztomi/testing/package/776f8cd6d5903762adae77c3f10ba7618c95e25c/include` in the compile command but the include path seems to be `/home/eric/.conan/data/thrift/0.9.3/sztomi/testing/build/776f8cd6d5903762adae77c3f10ba7618c95e25c/thrift/lib/cpp/src/thrift/TDispatchProcessor.h`

**Comment by EricWF** [comment] 2016-12-29 21:13
> but the include path seems to be /home/eric/.conan/data/thrift/0.9.3/sztomi/testing/build/776f8cd6d5903762adae77c3f10ba7618c95e25c/thrift/lib/cpp/src/thrift/TDispatchProcessor.h

Nevermind that's the build patch. It seems that your conan package file for `thrift` doesn't correctly install the headers. The include path used by my build doesn't exist.

**Comment by EricWF** [comment] 2016-12-29 21:16
Actually it seems like all of the generated conan include paths are wrong. I'm giving up trying to reproduce this myself.

**Comment by sztomi** [comment] 2016-12-29 22:02
Thanks for the feedback. All paths should be in /package/include BTW. I can
get back to you in a few days with a more minimal repro.

**Comment by EricWF** [comment] 2017-01-02 20:37
>  I can get back to you in a few days with a more minimal repro.

Alternatively you can just let me know when your original build instructions work.

**Comment by sztomi** [comment] 2017-01-03 10:55
Thanks. What I'm going to do is remove the other other libraries from the benchmark, because they are not needed for the repro which will hopefully make the benchmark trivial to build. rpclib is self-contained so it should build easily.

**Comment by sztomi** [comment] 2017-01-04 21:31
well, I have some doubts about the reproducability of this issue. I tried building the stripped version in a VM with little installed (to make sure it builds elsewhere) and I wasn't able to reproduce it in the VM nor on my physical machine later. If you still wish to take a look, you can find the intended repro here: https://github.com/rpclib/benchmarks/tree/getting-stuck-repro

**Comment by EricWF** [comment] 2017-01-17 01:43
Closing since it's no longer reproducible.

**Closed by EricWF** 2017-01-17 01:43 UTC
