### ISSUE TITLE
fix the types of iteration counts throughout

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#141] opened 2015-09-30 17:26 UTC
there's some confusion between size_t and int64_t in the codebase. These should be cleaned up.

iteration counts should be size_t (unsigned and large).

**Comment by EricWF** [comment] 2016-08-30 09:02
Closing this bug.

1. It's a year old.
2. It's a duplicate of #147 (albeit older).
3. int64_t still exists but not within iteration counts.

**Closed by EricWF** 2016-08-30 09:02 UTC
