### ISSUE TITLE
Explanation of the benchmark results

### ISSUE THREAD

**Issue by zack-snyder** [google/benchmark#397] opened 2017-06-02 13:48 UTC
1)
Is there an explanation of the standard benchmark table results?
```
Time: ?
CPU: ?
Iterations: ?
```
What is this exactly, and didn't find a clear explanation of this in the documentation.
2)
I put a sleep(100) into a while loop with some code.
For unknown reason we got 0ns at the  CPU column.
Although there were some code which does some calculation.
```
 while (state.KeepRunning())
 {
     sleep(100);
     benchmark::DoNotOptimize(some_func());
 }
```
3)
How big is the time out of all iterations?
```
static int result = 0;
 while (state.KeepRunning())
 {
     sleep(100);
     std::cout << ++result << std::endl;
 }
```
He printed till 111 and said iterations: 100
Why?

**Comment by EricWF** [comment] 2017-06-02 20:54
> It printed till 111 and said iterations: 100. Why?

Because the benchmark is tested a couple of times with different iteration counts to determine the correct count to use. After it finds an iteration count that causes the benchmark to run for a significant enough period of time it reports only that run, and not the test runs before it.

Resetting `result` to 0 at the start of the benchmark will show you this.

> Is there an explanation of the standard benchmark table results?

Time: The average wall time per iteration.

CPU:  The average CPU time per iteration. By default this clock is used when determining the amount of iterations to run. When you sleep your process it is no longer accumulating CPU time. I'm assuming `some_func()` is almost trivial, and that the compiler optimized almost all of it away. (`DoNotOptimize` is not magical and needs to be used very carefully. See https://github.com/google/benchmark#preventing-optimisation) 

Iterations: The number of iterations the benchmark ran. (See https://github.com/google/benchmark#controlling-number-of-iterations)

Perhaps somebody should add basic documentation about the output information.

**Comment by zack-snyder** [comment] 2017-06-07 13:09
1)
I do some initialization before the loop.
Will this also be included in the measurement?
Something like this:
```
static void BM_somefunc(benchmark::State& state)
{
    auto foo = do_some_init();
    while (state.KeepRunning())
    {
        do_some_calculation(foo);
    }
}
```
2)
I get sometimes following results
```
---------------------------------------------------------
Benchmark                  Time           CPU Iterations
---------------------------------------------------------
BM_fastFuncReturn      16327 ns      16392 ns      44800
BM_slowFuncReturn      17499 ns      16881 ns      40727
```
You see that the CPU time is in one case higher. How can this be?

**Comment by dominichamon** [comment] 2017-06-07 16:06
1. no it won't. and if you want to do some reinitialization in the loop you
can use PauseTiming and ResumeTiming.
2. because slowFuncReturn is slower?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by zack-snyder** [comment] 2017-06-09 11:44
How can the CPU timer higher, then the wall clock time?
How is the CPU time measured, with ticks?

**Comment by werdna87** [comment] 2017-06-09 18:13
I believe there might be a few ways. the most obvious is if your test uses multiple threads

**Comment by zack-snyder** [comment] 2017-06-12 08:43
no, there are no multiple threads involved

**Comment by HaoQChen** [comment] 2020-07-05 11:08
> > It printed till 111 and said iterations: 100. Why?
> 
> Because the benchmark is tested a couple of times with different iteration counts to determine the correct count to use. After it finds an iteration count that causes the benchmark to run for a significant enough period of time it reports only that run, and not the test runs before it.
> 
> Resetting `result` to 0 at the start of the benchmark will show you this.
> 
> > Is there an explanation of the standard benchmark table results?
> 
> Time: The average wall time per iteration.
> 
> CPU: The average CPU time per iteration. By default this clock is used when determining the amount of iterations to run. When you sleep your process it is no longer accumulating CPU time. I'm assuming `some_func()` is almost trivial, and that the compiler optimized almost all of it away. (`DoNotOptimize` is not magical and needs to be used very carefully. See https://github.com/google/benchmark#preventing-optimisation)
> 
> Iterations: The number of iterations the benchmark ran. (See https://github.com/google/benchmark#controlling-number-of-iterations)
> 
> Perhaps somebody should add basic documentation about the output information.

are you sure `time` is `The average wall time per iteration.`?

**Comment by HaoQChen** [comment] 2020-07-05 11:30
In linux, it seems to use `clock_gettime` function to get thread time and process time

see [src/timers.cc](src/timers.cc) line 130 and 174

**Comment by LebedevRI** [comment] 2020-07-08 11:31
Regarding documentation, it's a problem or knowledge.
Those who know the answers, know the answers, and don't airlessness think
that some particular thing is missing from the docs/is hard to understand.
Which can of course not be so for new users.

So i think it would be useful if someone could actually comply the list of topics
that seem to be not widely represented in docs, and then someone who can,
would document them.

**Comment by GACLove** [comment] 2021-01-27 07:28
https://pythonspeed.com/articles/blocking-cpu-or-io/  time and cpu time.   May be help you

**Comment by dominichamon** [comment] 2021-04-27 12:48
closing this out as a specific issue, but i remain open to anyone who wants to enhance the documentation further.

**Closed by dominichamon** 2021-04-27 12:48 UTC

**Comment by sketch34** [comment] 2024-06-18 04:40
> Is there an explanation of the standard benchmark table results?
> Time: ?
> CPU: ?
> Iterations: ?

Seems like some kind of anti-pattern is at play here. The exact same issue is present in Catch2's benchmarking documentation. Nowhere in the docs does it describe the meaning of the columns in the output and we're left guessing.

**Comment by dmah42** [comment] 2024-06-18 08:16
"
closing this out as a specific issue, but i remain open to anyone who wants to enhance the documentation further.

"

The [user guide](https://google.github.io/benchmark/user_guide.html) has sections on CPU Timers and Manual Timing, as well as describing real-time measurements.  i agree that it could be formatted better, but i don't think it's reasonable to say people are left guessing when there is documentation available.

what anti-pattern are you describing exactly?  poor documentation for open source projects or something more specific?

**Comment by LebedevRI** [comment] 2024-06-18 19:42
Time - time passed on the clock that is physically located on the wall in your room.
CPU - roughly, the number of CPU cycles spent. May either be for all threads, or the main thread, depending on particular configuration.
Iterations - how many times the code under benchmark has been re-run during that time.

**Comment by sketch34** [comment] 2024-06-19 02:22
@dmah42 No not poor documentation generally, the docs for `benchmark` look really quite good. But I was struck by how the docs for both Catch2's Benchmarking and then Google Benchmark both omit any specific description of the output they generate. This seems quite strange given the main point is to produce this output and interpret it.

So I wonder if there is an anti-pattern at play. Something like the [Curse of Knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge) occurring in developers because they have looked at the output many 1000s of times to the point where it is subconsciously assumed to be obvious. Or perhaps some reluctance to document since the simple labels of "Time", "CPU", and "Iterations" actually require somewhat elaborate explanations to understand properly, as they are produced by nontrivial means (I've encountered this in myself... "phew, this will actually take some explaining!").

> The [user guide](https://google.github.io/benchmark/user_guide.html) has sections on CPU Timers and Manual Timing
There is still some inference required and some ambiguity. Is "CPU Time" the value that gets output as "CPU"? I don't see any way to precisely infer the "Time" column's semantics. There just needs to be a section "Output" which provides a rigorous definition of each output category and exactly how the output values are produced.

**Comment by LebedevRI** [comment] 2024-06-19 02:32
TLDW: patches welcomed.

**Comment by dmah42** [comment] 2024-06-19 08:53
that's totally fair, and i think part of the issue is that when this was open-sourced (12 years ago or something? :|) i basically copied the internal documentation at the time, and have iterated or extended it rather than having a ground up rethink of the docs.

i would really like help getting the documentation into shape as i'm not a good technical writer and, as you suggest, i've been working on this project for so long that it's not obvious to me what's missing.

"patches welcome" can sound dismissive but i mean it: i don't think this is something i can do alone and i welcome any attempt to fill these holes.
