### ISSUE TITLE
[BUG] compare.py: OVERALL_GEOMEAN does not work in filters and benchmarksfiltered modes

### ISSUE THREAD

**Issue by chfast** [google/benchmark#1477] opened 2022-08-31 07:09 UTC
**Describe the bug**
When using `compare.py filters` or `compare.py benchmarksfiltered` the computed `OVERALL_GEOMEAN` is always 0.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Linux
  - Compiler and version: Python 3.10.4

**To reproduce**
1. Generate some benchmark results: `results.json`
2. `compare.py filters results.json A B`
3. `OVERALL_GEOMEAN                                           +0.0000         +0.0000             0             0             0             0`

**Expected behavior**
The `OVERALL_GEOMEAN` should be computed for the filtered results comparison.

**Comment by matta** [comment] 2022-09-08 17:03
Could this be a duplicate of #1482 which I filed yesterday? If not, could you provide a `results.json` that reproduces the problem?

**Comment by LebedevRI** [comment] 2022-09-08 17:27
Please reopen if still reproduces.

**Closed** 2022-09-08 17:27 UTC
