### ISSUE TITLE
Better support for fixture templates

### ISSUE THREAD

**Issue by dscole** [google/benchmark#698] opened 2018-10-05 14:05 UTC
This is a feature request to have a mechanism like googletest's [Typed Tests](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#typed-tests) and [Type Parameterized Tests](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#type-parameterized-tests).
Although you can use benchmark's current [templated-fixtures](https://github.com/google/benchmark#templated-fixtures), it's very inconvenient to use, because I have to define the test function for each separaterly:
```
BENCHMARK_TEMPLATE_F(MyFixture, IntTest, int)(benchmark::State& st) {
   for (auto _ : st) {
     ...
  }
}
BENCHMARK_TEMPLATE_F(MyFixture, DoubleTest, double)(benchmark::State& st) {
   for (auto _ : st) {
     ...
  }
}
```
Where what I would really like to do is:
```
using MyTypes = ::benchmark::Types<char, int, double>;
TYPED_BENCHMARK_CASE(FooTest, MyTypes);

BENCHMARK_TYPED_F(MyFixture, Test)(benchmark::State& st) {
   for (auto _ : st) {
     ...
  }
}
```

**Comment by marehr** [comment] 2018-10-30 12:47
Is this a duplicate of #541?

**Closed** 2018-10-30 14:43 UTC

**Comment by BigSeb** [comment] 2020-07-23 15:58
I don't think this is a duplicate of #541. This current issue is trying to prevent replicating the same benchmark function for multiple types. Having to repeat implementation of BENCHMARK_TEMPLATE_F for different types is inconvenient. BENCHMARK_F and BENCHMARK_DEFINE_F allow us to simplify template function implementation. Why not do the same when using custom Fixtures.

I take the previous example/proposal:
```
BENCHMARK_TYPED_F(MyFixture, Test)(benchmark::State& st) {
   for (auto _ : st) {
     ...
  }
}
```

There should be a way to register template fixtures similar to how Templated Benchmarks are registered (see https://github.com/google/benchmark#templated-benchmarks), ex:
```
BENCHMARK_TEMPLATE_REGISTER_F(MyFixture, Test, char)
BENCHMARK_TEMPLATE_REGISTER_F(MyFixture, Test, int)
BENCHMARK_TEMPLATE_REGISTER_F(MyFixture, Test, double)
```

Where this issue is similar to #541 is to simplify usage of BENCHMARK_TEMPLATE_REGISTER_F by specifying a list instead, similar to GoogleTest, ex:
```
using MyTypes = ::benchmark::Types<char, int, double>;
TYPED_BENCHMARK_CASE(FooTest, MyTypes);
```

**Comment by BigSeb** [comment] 2020-07-23 18:00
The current workaround to limit repeating the same code is to unify the benchmark implementation in a common function (in the fixture for example). See the following example:

```
template <class... Args>
class MyFixture : public benchmark::Fixture
{
protected:
    virtual void BenchmarkCase(benchmark::State& st) override
    {
        for (auto _ : st) {
            //...
        }
    }
};

BENCHMARK_TEMPLATE_DEFINE_F(MyFixture, Test_char, char)(benchmark::State& state)
{
    MyFixture::BenchmarkCase(state);
}

BENCHMARK_TEMPLATE_DEFINE_F(MyFixture, Test_int, int)(benchmark::State& state)
{
    MyFixture::BenchmarkCase(state);
}

BENCHMARK_TEMPLATE_DEFINE_F(MyFixture, Test_double, double)(benchmark::State& state)
{
    MyFixture::BenchmarkCase(state);
}

BENCHMARK_REGISTER_F(MyFixture, Test_char);
BENCHMARK_REGISTER_F(MyFixture, Test_int);
BENCHMARK_REGISTER_F(MyFixture, Test_double);
```

I think it could be simplified as it was done with Templated Benchmark functions.

**Comment by krzikalla** [comment] 2020-08-03 14:10
I do the following thing:

```
#define BENCHMARK_TEMPLATE_METHOD_F(BaseClass, Method, ...)       \
  class BaseClass##_##Method##_Benchmark : public BaseClass<__VA_ARGS__> { \
   public:                                                                 \
    BaseClass##_##Method##_Benchmark() : BaseClass<__VA_ARGS__>() {        \
      this->SetName(#BaseClass "<" #__VA_ARGS__ ">/" #Method);             \
    }                                                                      \
   protected:                                                              \
    virtual void BenchmarkCase(::benchmark::State& st) {                   \
      this->Method(st);                                                    \
    }                                                                      \
  };

#define BENCHMARK_TEMPLATE_REGISTER_F(BaseClass, Method, ...) \
  class BaseClass##_##Method##_Benchmark##__VA_ARGS__ : public BaseClass##_##Method##_Benchmark<__VA_ARGS__> { \
   public:                                                                 \
    BaseClass##_##Method##_Benchmark##__VA_ARGS__() : BaseClass##_##Method##_Benchmark<__VA_ARGS__>() {        \
      this->SetName(#BaseClass "<" #__VA_ARGS__ ">/" #Method);             \
    }                                                                      \
  };                                                                       \
  BENCHMARK_PRIVATE_REGISTER_F(BaseClass##_##Method##_Benchmark##__VA_ARGS__)
```

Write your method as a member function in your fixture. Let's say, class is Foo (templated by size_t), method is bar. Then write:

```
template<size_t Blocksize>
BENCHMARK_TEMPLATE_METHOD_F(Foo, bar, Blocksize)

BENCHMARK_TEMPLATE_REGISTER_F(Foo, bar, 5)->Arg(100)->Arg(1000)->Arg(1000000)
  ->Threads(1)->Threads(12);
```

For me this has the advantage, that you can specify different argument sets for different template arguments. However I admit, that others might like a solution with a type list (similar to gtest), which uses the same argument set for all template arguments.
