### ISSUE TITLE
Does this library work under Windows?

### ISSUE THREAD

**Issue by navia1991** [google/benchmark#368] opened 2017-04-10 15:49 UTC
I am currently using VS2017 and i ran into errors when i tried to build in VS. 
For example, LINK : fatal error LNK1104: cannot open file 'pthread.lib'.

I d like to ask is the 'compiler support' a necessary for using this library?
Such as i need GCC, clang, VS, Intel 2015 Update 1 ALL intalled?
Thanks!

**Comment by dominichamon** [comment] 2017-04-10 15:54
There are windows users, so i believe it should. When you run cmake to
generate the VS solution i believe it will check for the pthread
dependency... perhaps you don't have pthread available?

I'm afraid i haven't kept up with Windows development so i can't help much.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by lysevi** [comment] 2017-04-12 12:40
hello.

i build benchmarklib as cmake subproject
```cmake
if(DARIADB_ENABLE_BENCHMARKS)
   set(BENCHMARK_ENABLE_TESTING OFF)
   add_subdirectory(extern/benchmark)
   include_directories(extern/benchmark/include)
   set_target_properties(benchmark PROPERTIES FOLDER Extern)
endif(DARIADB_ENABLE_BENCHMARKS)
```

where 'extern/benchmark' is a git submodule. But when i build in msvc 2015, google.benchmark always build as shared dll, not as static. this is a bug? i see you build scripts, and you not set library type of benchmark lib. 

```cmake
add_library(benchmark ${SOURCE_FILES})
```

i think, that should see be like this
```cmake
add_library(benchmark STATIC ${SOURCE_FILES})
```

**Comment by KindDragon** [comment] 2017-04-14 16:59
It's work on Windows with several compilers https://ci.appveyor.com/project/google/benchmark

**Comment by EricWF** [comment] 2017-04-15 05:03
On Wed, Apr 12, 2017 at 6:40 AM, Sergey Lyubimov <notifications@github.com>
wrote:

> hello.
>
> i build benchmarklib as cmake subproject
>
> if(DARIADB_ENABLE_BENCHMARKS)
>    set(BENCHMARK_ENABLE_TESTING OFF)
>    add_subdirectory(extern/benchmark)
>    include_directories(extern/benchmark/include)
>    set_target_properties(benchmark PROPERTIES FOLDER Extern)endif(DARIADB_ENABLE_BENCHMARKS)
>
> where 'extern/benchmark' is a git submodule. But when i build in msvc
> 2015, google.benchmark always build as shared dll, not as static. this is a
> bug? i see you build scripts, and you not set library type of benchmark lib.
>
Google Benchmark builds a static/shared library depending on the value of
BUILD_SHARED_LIBS. On UNIX platforms this defaults to OFF so a static
library is built. Are you setting this value to ON?

Also you should build Google Benchmark as an External Project
<https://cmake.org/cmake/help/v3.0/module/ExternalProject.html>, not using
`add_subdirectory`.

**Comment by lysevi** [comment] 2017-04-15 05:14
>> Are you setting this value to ON?

no, i'm no set this variable on build script or manually.

**Comment by EricWF** [comment] 2017-04-15 06:25
Yes this library works under Windows, and we have multiple Windows builders that test each commit.

@navia1991 This issue is likely on your end, likely the weirdness you're doing to setup/configure the CMake project.

Closing because the library works on Windows. @navia1991 Please open a new, more specific issue if you find the cause of your problem and it's Google Benchmark's fault.

**Closed by EricWF** 2017-04-15 06:25 UTC

**Comment by EricWF** [comment] 2017-04-15 06:33
>> Are you setting this value to ON?
> no, i'm no set this variable on build script or manually.

@lysevi Well somebody is setting it to `ON`. I just checked the Windows builders and they generate a static library by default. Here is the doc for [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html)
