### ISSUE TITLE
gcc 5.2.1/6.1.1: error: inconsistent operand constraints in an ‘asm’

### ISSUE THREAD

**Issue by zabereer** [google/benchmark#213] opened 2016-05-17 20:17 UTC
Compilation fails when using benchmark::DoNotOptimize on an array:

``
In file included from benchmark/include/benchmark/benchmark.h:18:0,
                 from bm_boost_crc.cpp:1:
benchmark/include/benchmark/benchmark_api.h: In function ‘void {anonymous}::boost_crc6(benchmark::State&)’:
benchmark/include/benchmark/benchmark_api.h:217:54: error: inconsistent operand constraints in an ‘asm’
     asm volatile("" : "+rm" (const_cast<Tp&>(value)));
``

Although gcc documenation on asm contraints indicates they should be adjacent I find inserting a comma ("+r,m") solves this problem. However it then does not work for functions returning an integral like boost::crc_optimal's checksum method:
> value_type  checksum() const;

I find the best solution to both is to use a template for pointers separately.
I have a patch that seem to work in all cases I have encountered so far.

**Comment by EricWF** [comment] 2016-05-17 20:20
Urg. so the "rm" used to mean put this value in a register if possible, otherwise put it in memory. I think there's another way to say this that will avoid the conflicting constraints error.

**Comment by EricWF** [comment] 2016-05-17 22:41
I cannot reproduce the error your seeing with GCC. (See https://goo.gl/krlgJM).

Could you please try changing "+rm" to "+g" and tell me if that works?

**Comment by EricWF** [comment] 2016-05-17 22:58
OK so I managed to reproduce here: https://goo.gl/CJqGjJ. Unfortunately the change to "+g" doesn't work. Versions of GCC prior to v5 ICE on this code. Changing "+rm" to "+g" still emits the same error. I'll file a GCC bug since "+g" shouldn't have any conflicting constraints since its obviously a single constraint.

**Comment by zabereer** [comment] 2016-05-18 06:25
In hindsight I realise it is wrong to try to force a memory constraint on all non-pointer types. 
Many thanks for filing the gcc bug, that is kind of you.

**Comment by EricWF** [comment] 2016-05-23 19:08
GCC Bug Filed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71246

**Comment by EricWF** [comment] 2016-07-01 23:12
I think this has been fixed in master. Please reopen if I'm incorrect.

**Closed by EricWF** 2016-07-01 23:12 UTC
