### ISSUE TITLE
check.h(41): warning C4722: 'benchmark::internal::CheckHandler::~CheckHandler': destructor never returns, potential memory leak

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [google/benchmark#948] opened 2020-03-26 09:18 UTC
check.h(41): warning C4722: 'benchmark::internal::CheckHandler::~CheckHandler': destructor never returns, potential memory leak

Compiled with Visual Studio 2019 Professional 16.5.1 on Windows 10 Prof. 1903.

**Comment by dominichamon** [comment] 2021-05-08 18:06
duplicate of #826

**Closed by dominichamon** 2021-05-08 18:06 UTC
