### ISSUE TITLE
[FR] Automatically include Google Test dependency

### ISSUE THREAD

**Issue by mcandre** [google/benchmark#1119] opened 2021-04-25 23:36 UTC
**Is your feature request related to a problem? Please describe.**

The installation steps involve a manual dependency management step:

```
# Benchmark requires Google Test as a dependency. Add the source tree as a subdirectory.
$ git clone https://github.com/google/googletest.git benchmark/googletest
```

**Describe the solution you'd like**

Use git submodules to automate this process.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Describe alternatives you've considered**

* Use cmake to automate dependency installation.
* Drop dependency on Google Test.

**Comment by LebedevRI** [comment] 2021-04-26 07:15
Duplicate of #1092 / etc

**Closed by LebedevRI** 2021-04-26 07:15 UTC
