### ISSUE TITLE
Some small warnings in MSVC

### ISSUE THREAD

**Issue by riccozzz** [google/benchmark#786] opened 2019-03-19 16:56 UTC
Getting the following warnings when building with the latest VS2019 RC (Version 19.20.27404).

```
benchmark_runner.cc(258): warning C4244: 'initializing': conversion from 'double' to 'size_t', possible loss of data
benchmark_runner.cc(258): warning C4244: 'initializing': conversion from 'double' to 'const size_t', possible loss of data
check.h(41) : warning C4722: 'benchmark::internal::CheckHandler::~CheckHandler': destructor never returns, potential memory leak
```

The first is a simple fix, but not sure about C4722 - should that warning be disabled (or just ignored)?

**Comment by dominichamon** [comment] 2021-05-08 08:46
Completely missed this one: The former should be fixed with a `static_cast`, the third is a valid warning but as it's the `CheckHandler` it's ignorable. I think we should probably pragma that off, but given it's in a header maybe we just disabled the warning globally.

**Comment by imrichardcole** [comment] 2024-09-07 12:47
Unable to reproduce these,  not sure they'd still be possible now we're using /W4 and /WX.

Propose this is closed.

**Closed** 2024-09-07 14:32 UTC
Labels: bug, good first issue, help wanted, os:windows
