### ISSUE TITLE
[BUG] In 1.8.4 the suffix of lib/libbenchmark.so.1 went backwards: lib/libbenchmark.so.0

### ISSUE THREAD

**Issue by yurivict** [google/benchmark#1804] opened 2024-06-16 17:25 UTC
**Describe the bug**
Is this intended?

**System**
Which OS, compiler, and compiler version are you using:
  - OS: FreeBSD 14.1
  - Compiler and version: clang-18

**Comment by LebedevRI** [comment] 2024-06-16 17:52
Duplicate of #1792.

**Closed by LebedevRI** 2024-06-16 17:52 UTC
