### ISSUE TITLE
Windows: support static CRT runtime in CMakeLists.txt

### ISSUE THREAD

**Issue by KindDragon** [google/benchmark#386] opened 2017-05-10 20:48 UTC
Something like that https://github.com/grpc/grpc/blob/master/cmake/msvc_static_runtime.cmake

**Comment by dominichamon** [comment] 2021-04-27 12:47
Can someone explain the potential benefit? I'm finding it hard to have an opinion without understanding what problem this solves.

**Comment by scott-ferguson-unity** [comment] 2022-04-22 15:08
The MSVC static/dynamic CRT's aren't compatible so the project being benchmarked is linked with the MSVC static CRT you get a [linker error](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2038?view=msvc-170) since `benchmark.lib` is linked with the MSVC dynamic CRT (which is the default).

But no support needs to be added,  passing ` -DCMAKE_CXX_FLAGS_RELEASE=/MT` when building the benchmark library will link `benchmark.lib` with the static CRT.

**Comment by imrichardcole** [comment] 2024-09-06 19:58
Duplicate (I believe) of https://github.com/google/benchmark/issues/1655

**Comment by LebedevRI** [comment] 2024-09-06 20:58
I suppose it's the other way around, but sure, let's go with the more recent one.
Duplicate of https://github.com/google/benchmark/issues/1655.

**Closed by LebedevRI** 2024-09-06 20:58 UTC
Labels: enhancement, os:windows
